networks:
  traefik:
    external: true

services:
  languagetool:
    container_name: languagetool
    image: ghcr.io/batinicaz/languagetool:1.1.4@sha256:b6f073d38ade6a37a13b62d00e99cddd617af348278172880f97942d05c442d1
    restart: unless-stopped
    read_only: true
    user: "783:783"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      - /opt/data/languagetool/ngrams:/ngrams:ro,z
    environment:
      - LISTEN_PORT=8010
      - JAVA_XMS=512m
      - JAVA_XMX=2g
    networks:
      - traefik
