networks:
  traefik:
    external: true

services:
  languagetool:
    container_name: languagetool
    image: ghcr.io/batinicaz/languagetool:1.1.6@sha256:0f57f4b7f4d7285d0799e6c38b3615b951ded424ab68757031f57b59e0217eef
    restart: unless-stopped
    read_only: true
    user: "783:783"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    volumes:
      - /opt/data/languagetool/ngrams:/ngrams:ro,z
    environment:
      - LISTEN_PORT=8010
      - JAVA_XMS=512m
      - JAVA_XMX=2g
    networks:
      - traefik
