infisical:
  address: https://eu.infisical.com
auth:
  type: universal-auth
  config:
    client-id: /run/secrets/client-id
    client-secret: /run/secrets/client-secret
templates:
  - source-path: /etc/infisical/templates/freshrss.env.tmpl
    destination-path: /opt/secrets/freshrss.env
    config:
      polling-interval: 5m
  - source-path: /etc/infisical/templates/planka.env.tmpl
    destination-path: /opt/secrets/planka.env
    config:
      polling-interval: 5m
  - source-path: /etc/infisical/templates/planka-postgres.env.tmpl
    destination-path: /opt/secrets/planka-postgres.env
    config:
      polling-interval: 5m
  - source-path: /etc/infisical/templates/nitter.env.tmpl
    destination-path: /opt/secrets/nitter.env
    config:
      polling-interval: 5m
  - source-path: /etc/infisical/templates/nitter-sessions.tmpl
    destination-path: /opt/secrets/nitter-sessions.jsonl
    config:
      polling-interval: 5m
  - source-path: /etc/infisical/templates/nitter-config.conf.tmpl
    destination-path: /opt/secrets/nitter.conf
    config:
      polling-interval: 5m
  - source-path: /etc/infisical/templates/redlib.env.tmpl
    destination-path: /opt/secrets/redlib.env
    config:
      polling-interval: 5m
  - source-path: /etc/infisical/templates/fulltextrss-config.php.tmpl
    destination-path: /opt/secrets/fulltextrss-config.php
    config:
      polling-interval: 5m
  - source-path: /etc/infisical/templates/ghcr-token.tmpl
    destination-path: /opt/secrets/ghcr-token
    config:
      polling-interval: 5m
